[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt && npm install && python manage.py collectstatic --noinput && gunicorn pawpect_project.wsgi"
  publish = "staticfiles"

[dev]
  command = "python manage.py runserver"
  port = 8000
